[[service]]
service_name = "NetworkManager.service"
friendly_name = "Network manager"

[[service]]
service_name = "power-profiles-daemon.service"
friendly_name = "Power profiles"
show_logs = true

[[service]]
service_name = "display-manager.service"
friendly_name = "Display Manager (sddm)"
show_logs = false

